FROM debian:testing

RUN echo 'Acquire::http { Proxy "http://172.17.0.1:3142"; };' >> /etc/apt/apt.conf.d/01proxy
RUN apt-get -y update && apt-get -y install ansible

# CMD /bin/bash /home/jez/.dotfiles/box-config/scripts/box-config bootstrap
