#!/usr/bin/zsh

if which pacman &> /dev/null; then
  echo "Performing pacman system upgrade"
  echo "================================"
  sudo pacman -Syu
elif which apt-get &> /dev/null; then
  echo "\nPerforming apt-get system upgrade"
  echo "================================"
  sudo apt-get update
  sudo apt-get upgrade
fi

echo "\nUpdating puppet configuration"
echo "============================="
(cd /etc/box-config && sudo -E git pull)

echo "\nUpdating dotfiles"
echo "================="
(cd ~/.dotfiles && git pull && git submodule update)

echo "\nApplying updated puppet configuration"
echo "====================================="
box-config apply
