---
# We need this for ansible_lsb facts later
- name: ensure lsb-release is installed
  apt: pkg=lsb-release state=latest
- name: reload facts
  setup:

# Set up user and group
- name: ensure group exists
  group: name=jez
- name: ensure user exists
  user: name=jez group=jez comment="Jez Cope" home="/home/jez"

# Ensure all packages are available on debian
- name: add non-free and contrib
  apt_repository:
    repo: "deb http://ftp.uk.debian.org/debian/ {{ ansible_lsb.codename }} non-free contrib"
    filename: debian-extra
  when: ansible_lsb.id == "Debian"
- apt: update_cache=true
  when: ansible_lsb.id == "Debian"

# Install base required packages
- name: install shell and utilities
  apt: pkg={{ item }} state=latest
  with_items:
    - zsh
    - tmux
    - unzip
    - unison
    - apg                       # password generator
    - mc                        # Midnight Commander
- name: install gnupg and tools
  apt: pkg={{ item }} state=latest
  with_items:
    - gnupg2
    - scdaemon
    - pcscd
    - libpcsclite-dev
- name: install network utils
  apt: pkg={{ item }} state=latest
  with_items:
    - ldap-utils
    - gnutls-bin
    - ssh
    - lftp
    - whois
    - curl
    - wget 
- name: install version control tools
  apt: pkg={{ item }} state=latest
  with_items: [bzr, mercurial, cvs]
- name: install programming languages and tools
  apt: pkg={{ item }} state=latest
  with_items:
    - ruby
    - python3
    - python3-pip
    - sbcl
    - rlwrap
- name: install software development tools 
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - autoconf
    - automake
    - shellcheck
    - silversearcher-ag
    - colordiff
    - wdiff
- name: install rvm prerequisites
  apt: pkg={{ item }} state=latest
  with_items: [gawk, libreadline6-dev, zlib1g-dev, libssl-dev, libyaml-dev, libsqlite3-dev, sqlite3, libgdbm-dev, libncurses5-dev, libtool, bison, pkg-config, libffi-dev]
- name: install irc client
  apt: pkg=weechat state=latest
- name: install mail tools
  apt: pkg={{ item }} state=latest
  with_items:
    - offlineimap
    - maildir-utils
- name: install filesystems
  apt: pkg={{ item }} state=latest
  with_items:
    - cifs-utils
    - winbind
    - exfat-utils
    - exfat-fuse
- name: install texlive
  apt: pkg={{ item }} state=latest
  with_items: [texlive, texlive-latex-extra, texlive-xetex, texlive-science, texinfo, latexmk]
- name: install other utilities
  apt: pkg={{ item }} state=latest
  with_items:
    - imagemagick
    - qrencode
