---
- name: install terminal
  apt: pkg=sakura state=latest
- name: install text editors
  apt: pkg={{ item }} state=latest
  with_items:
    - emacs24
    - vim-gtk
- name: install web browsers
  apt: pkg={{ item }} state=latest
  with_items:
    - '{{ (ansible_distribution == "Ubuntu") | ternary("chromium-browser", "chromium") }}'
    - '{{ (ansible_distribution == "Ubuntu") | ternary("firefox", "firefox-esr") }}'
- name: install mail clients
  apt: pkg={{ item }} state=latest
  with_items:
    - mu4e
    - maildir-utils-extra
    - libgmime-2.6-dev
    - libxapian-dev
    - claws-mail
- name: install office software
  apt: pkg={{ item }} state=latest
  with_items:
    - libreoffice
    - libreoffice-gtk
    - abiword
- name: add dropbox repository key
  apt_key: id=1C61A2656FB57B7E4DE0F4C1FC918B335044912E keyserver=pgp.mit.edu state=present
- name: add dropbox repository
  apt_repository:
    repo: "deb http://linux.dropbox.com/{{ ansible_lsb.id|lower }} {{ ansible_lsb.codename }} main"
    filename: dropbox
- apt: update_cache=true
- name: install file management tools
  apt: pkg={{ item }} state=latest
  with_items:
    - unison-gtk
    - python-gpgme
    - dropbox
    - caja
    - atril
    - filezilla
- name: install software development tools
  apt: pkg={{ item }} state=latest
  with_items:
    - zeal
- name: install yubikey tools
  apt: pkg={{ item }} state=latest
  with_items:
    - yubikey-personalization
    - yubikey-personalization-gui
- name: install communication tools
  apt: pkg={{ item }} state=latest
  with_items:
    - skype
    - pidgin
    - hexchat
- name: install x utilities
  apt: pkg={{ item }} state=latest
  with_items:
    - xbacklight
    - xclip
- name: install network tools
  apt: pkg={{ item }} state=latest
  with_items:
    - linssid
- name: install productivity tools
  apt: pkg={{ item }} state=latest
  with_items:
    - workrave
- name: install audio tools
  apt: pkg={{ item }} state=latest
  with_items:
    - pavucontrol 
- name: install pdf-tools prerequisites
  apt: pkg={{ item }} state=latest
  with_items:
    - [libpng12-dev, libpoppler-glib-dev, libpoppler-private-dev]
