---
- hosts: localhost

  vars:
    node_config: "node/config/{{ ansible_fqdn }}.yaml"
    node_vars: "node/vars/{{ ansible_fqdn }}.yaml"

    box_user: jez
    box_group: jez
    box_home: "/home/{{ box_user }}"

    dotfiles: "{{ box_home }}/.dotfiles"

    tmux_status_style: "bg=green,fg=black"

  tasks:
    - name: update apt cache
    # - name: check for test environment
    #   set_fact:
    #     node_config: node/config/testing.yaml
    #     node_vars: node/vars/testing.yaml
    #   when: testing|default(false)
    - debug: msg="{{node_config}}; {{node_vars}}"
      apt: update_cache=yes cache_valid_time=86400 # update at most once a day
    - name: include node-specific variables
      include_vars: "{{ node_vars }}"
      when: node_vars|is_file
    - include: base.yaml
    - include: dotfiles.yaml
    - name: include node-specific config
      include: "{{ node_config }}"
