---
- hosts: localhost

  vars:
    node_config: "node/config/{{ ansible_fqdn }}.yaml"
    node_vars: "node/vars/{{ ansible_fqdn }}.yaml"

    box_user: jez
    box_group: jez
    box_home: "/home/{{ box_user }}"

    tmux_status_style: "bg=green,fg=black"

  tasks:
    - name: update apt cache
      apt: update_cache=true
    - name: check for test environment
      set_fact:
        node_config: node/config/testing.yaml
        node_vars: node/vars/testing.yaml
      when: testing|default(false)
    - debug: msg="{{node_config}}"
    - name: include node-specific variables
      include: "{{ node_vars }}"
      when: node_vars|is_file
    - include: base.yaml
    - name: include node-specific config
      include: "{{ node_config }}"
